<a href="https://colab.research.google.com/github/SinghJasvirX/githubnew/blob/main/DSE_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Given array:\n", arr)
#ndim
print("Number of dimensions:", arr.ndim)

Given array:
 [[1 2 3]
 [4 5 6]]
Number of dimensions: 2


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Given array:\n", arr)
#shape
print("Shape:", arr.shape)

Given array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [ ]:
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Given array:\n", arr1)
#reshape
arr2 = arr1.reshape(3, 2)
print("Reshaped array:\n", arr2)

Given array:
 [[1 2 3]
 [4 5 6]]
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
#empty
arr = np.empty(2, dtype = int) #dtype by default is float
print(arr)

[44090817        0]


In [ ]:
import numpy as np
#zeros
arr = np.zeros((3, 3), dtype = int) #dtype by default is float
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np
#ones
arr = np.ones((3, 3), dtype = int) #dtype by default is float
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np
x = [1, 2, 3, 4, 5, 6]
print("Python List:\n", x)
#asarray
arr = np.asarray(x, dtype = float)
print("Numpy array:\n", arr)

Python List:
 [1, 2, 3, 4, 5, 6]
Numpy array:
 [1. 2. 3. 4. 5. 6.]


In [ ]:
import numpy as np
x = [(1, 2, 3), (4, 5, 6)]
print("Python List:\n", x)
arr = np.asarray(x, dtype = float)
print("Numpy array:\n", arr)

Python List:
 [(1, 2, 3), (4, 5, 6)]
Numpy array:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
#itemsize
print("Size of individual element:", arr.itemsize, "bytes")

Size of individual element: 8 bytes


In [ ]:
import numpy as np
#arange
arr = np.arange(10, dtype = float)
print("Numpy array with 10 elements:\n", arr)

Numpy array with 10 elements:
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
import numpy as np
arr1 = np.arange(10)
#slicing examples
print(arr1[3:6])
print(arr1[::-1])
arr2 = arr1[6:8]
print(arr2)

[3 4 5]
[9 8 7 6 5 4 3 2 1 0]
[6 7]


In [ ]:
import numpy as np
arr = np.arange(10)
#using indexing and slicing
print("Initial array:\n", arr)
arr[3] = 1
arr[-1] = 0
arr[6:8] = np.array([2,0])
print("Final array:\n", arr)

Initial array:
 [0 1 2 3 4 5 6 7 8 9]
Final array:
 [0 1 2 1 4 5 2 0 8 0]


In [ ]:
import numpy as np
arr = np.arange(10)
print("Initial array:\n", arr)
#operations on numpy array
print("After operations:")
print(arr+5)
print(arr*3)
print(arr-2)

Initial array:
 [0 1 2 3 4 5 6 7 8 9]
After operations:
[ 5  6  7  8  9 10 11 12 13 14]
[ 0  3  6  9 12 15 18 21 24 27]
[-2 -1  0  1  2  3  4  5  6  7]


In [ ]:
import numpy as np
#linspace
arr = np.linspace(0, 10, num=20, endpoint=False)
print(arr)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [ ]:
import numpy as np
arr1 = np.array([[2, 3, 4 ,5], [4, 5, 5, 3]])
print("Array 1:\n", arr1, "\nShape:", arr1.shape)
arr2 = np.array([[6, 5, 5, 2], [8, 2, 5, 8]])
print("\nArray 2:\n", arr2, "\nShape:", arr2.shape)
#vstack
arr3 = np.vstack((arr1, arr2))
print("\nArray 1 & 2 vertically stacked:\n", arr3, "\nShape:", arr3.shape)
#hstack
arr4 = np.hstack((arr1, arr2))
print("\nArray 1 & 2 horizontally stacked:\n", arr4, "\nShape:", arr4.shape)

Array 1:
 [[2 3 4 5]
 [4 5 5 3]] 
Shape: (2, 4)

Array 2:
 [[6 5 5 2]
 [8 2 5 8]] 
Shape: (2, 4)

Array 1 & 2 vertically stacked:
 [[2 3 4 5]
 [4 5 5 3]
 [6 5 5 2]
 [8 2 5 8]] 
Shape: (4, 4)

Array 1 & 2 horizontally stacked:
 [[2 3 4 5 6 5 5 2]
 [4 5 5 3 8 2 5 8]] 
Shape: (2, 8)


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
print("Initial array:\n", arr1)
#power
arr2 = np.power(arr1, 2)
print("Every element squared:\n", arr2)
arr3 = np.power(arr1, 3)
print("Every element cubed:\n", arr3)

Initial array:
 [1 2 3 4]
Every element squared:
 [ 1  4  9 16]
Every element cubed:
 [ 1  8 27 64]


In [ ]:
import numpy as np
arr1 = np.array([35, 40, 30, 28, 29, 33])
print("Initial array:\n", arr1)
#conditional expressions
arr2 = arr1 > 30
print("\nLogical comparison (greater than 30):\n", arr2)
print("\nElements greater than 30:\n", arr1[arr2])

Initial array:
 [35 40 30 28 29 33]

Logical comparison (greater than 30):
 [ True  True False False False  True]

Elements greater than 30:
 [35 40 33]


In [ ]:
import numpy as np
arr1 = np.array([[True, False], [True, False]])
print("Array 1:\n", arr1)
arr2 = np.array([[False, True], [True, False]])
print("\nArray 2:\n", arr2)
#logical operations
print("\nArray 1 OR Array 2:\n", np.logical_or(arr1, arr2))
print("\nArray 1 AND Array 2:\n", np.logical_and(arr1, arr2))

Array 1:
 [[ True False]
 [ True False]]

Array 2:
 [[False  True]
 [ True False]]

Array 1 OR Array 2:
 [[ True  True]
 [ True False]]

Array 1 AND Array 2:
 [[False False]
 [ True False]]


In [ ]:
import numpy as np
arr1 = np.array([5, 10, 15, 20])
print("Array 1:\n", arr1)
arr2 = np.array([2, 4, 5, 7])
print("\nArray 2:\n", arr2)
#mod
print("\nAfter modulus:\n", np.mod(arr1, arr2))

Array 1:
 [ 5 10 15 20]

Array 2:
 [2 4 5 7]

After modulus:
 [1 2 0 6]


In [ ]:
import numpy as np
arr1 = np.array([5, 10, 15, 20])
print("Array 1:\n", arr1)
arr2 = np.array([2, 4, 5, 7])
print("\nArray 2:\n", arr2)
#remainder (same as mod)
print("\nAfter modulus:\n", np.remainder(arr1, arr2))

Array 1:
 [ 5 10 15 20]

Array 2:
 [2 4 5 7]

After modulus:
 [1 2 0 6]
